[web]
listen_addr = "127.0.0.1:8080"

[auth0]
domain = "glio.auth0.com"
callback_url = "http://localhost:8080/_auth/callback"
logout_url = "http://localhost:8080/_auth/logout"

[mailgun]
domain = "gliderlabs.com"
